export const ASSETS = {
  IMAGES: {
    HERO1: "/images/hero-section/hero1.png",
    HERO2: "/images/hero-section/hero2.png",
    HERO3: "/images/hero-section/hero3.png",
    HERO4: "/images/hero-section/hero4.png",
    IMAGE37: "/images/hero-section/image 37.png",
    IMAGE38: "/images/hero-section/image38.png",
    IMAGE_WHAT_WAITING: "/images/hero-section/what-are-you-waiting-for.png",
    LOGO: "/images/logo/USA-TYI-Logo.svg", 
    LOGO_UAE: "/images/logo/UAE-TYI-Logo.png",
    FOOTER_LOGO: "/images/logo/USA TYI New Logo 1.png",
    ICON_DOTS: "/images/icons/dot-icon.png",
    ICON_BLUESTAR: "/images/icons/bluestar.png",
    ICON_FLOWER: "/images/icons/flower.png",
    ICON_CERTIFICATE: "/images/icons/certificate-outline.png",
    ICON_RED_STAR: "/images/icons/red star.png",
    ICON_TARGET_SIX_LINES: "/images/icons/Target Six Lines.png",
    ICON_GLOBE_HANDS: "/images/icons/healthicons_world-care-outline.png",
    ICON_CROWN: "/images/icons/queen-crown.png",
    ICON_CASH: "/images/icons/hand-holding-usd.png",
    ICON_PATENT: "/images/icons/us-patent.png",
    ICON_TROPHY: "/images/icons/prime_trophy.png",
    PARTNER_DISCOVERSTEM: "/images/partners/discoverstem.png",
    CHALLENGE_HERO_LEFT: "/images/challenge/hero-left.png",
    CHALLENGE_HERO_MID_TOP: "/images/challenge/hero-mid-top.png",
    CHALLENGE_HERO_MID_BOTTOM: "/images/challenge/hero-mid-bottom.png",
    CHALLENGE_HERO_RIGHT: "/images/challenge/hero-right.png",
    CHALLENGE_RULES: "/images/challenge/rules.png",
    CHALLENGE_SCORE_1: "/images/challenge/score-1.png",
    CHALLENGE_SCORE_2: "/images/challenge/score-2.png",
    CHALLENGE_SCORE_3: "/images/challenge/score-3.png",
    CHALLENGE_CTA: "/images/challenge/cta.png",
    STEP_INTO_FUTURE: "/images/challenge/step.png",
    CHALLENGE_AWARDS_BG: "/images/challenge/awards-bg.png",
    PAST_WINNERS_HERO: "/images/past-winners/hero.png",
    PAST_WINNERS_VIDEO_BANNER: "/images/past-winners/video-banner.png",
    PAST_WINNERS_INNOVATION_1: "/images/past-winners/innovation-1.png",
    PAST_WINNERS_INNOVATION_2: "/images/past-winners/innovation-2.png",
    PAST_WINNERS_GUEST_1: "/images/past-winners/guest-1.png",
    PAST_WINNERS_GUEST_2: "/images/past-winners/guest-2.png",
    PAST_WINNERS_WINNER: "/images/past-winners/winner.png",
    PAST_WINNERS_1: "/images/past-winners/Image1.webp",
    PAST_WINNERS_2: "/images/past-winners/Image2.webp",
    PAST_WINNERS_3: "/images/past-winners/Image3.webp",
    PAST_WINNERS_4: "/images/past-winners/Image4.webp",
    PAST_WINNERS_5: "/images/past-winners/Image5.webp",
    PAST_WINNERS_6: "/images/past-winners/Image6.webp",
    PAST_WINNERS_7: "/images/past-winners/Image7.webp",
    PAST_WINNERS_8: "/images/past-winners/Image8.webp",
    PAST_WINNERS_9: "/images/past-winners/Image9.webp",
    PAST_WINNERS_10: "/images/past-winners/Image10.webp",
    PAST_WINNERS_11: "/images/past-winners/Image11.webp",
    PAST_WINNERS_12: "/images/past-winners/Image12.webp",
    PAST_WINNERS_13: "/images/past-winners/Image13.webp",
    PAST_WINNERS_14: "/images/past-winners/Image14.webp",
    PAST_WINNERS_15: "/images/past-winners/Image15.webp",
    SUBMIT_HERO: "/images/submit/hero.png",
    SUBMIT_STEP_1: "/images/submit/step-1.png",
    SUBMIT_STEP_2: "/images/submit/step-2.png",
    SUBMIT_STEP_3: "/images/submit/step-3.png",
    ABOUT_BOOKS: "/images/about/books.png",
    ABOUT_YOUNG_STUDENTS: "/images/about/young-students.png",
    ABOUT_CLOSE_UP: "/images/about/close-up.png",
    ABOUT_GROUP_LAPTOP: "/images/about/group-laptop.png",
    ABOUT_GLOBAL_UAE: "/images/about/global-uae.png",
    ABOUT_GLOBAL_USA: "/images/about/global-usa.png",
    PATENT_GLOBAL: "/images/patent/global.png",
PATENT_EDUCATION: "/images/patent/education.png",
PATENT_ROCKET: "/images/patent/growth.png",
PATENT_MONEY: "/images/patent/money.png",
PATENT_LOCK: "/images/patent/protection.png",
PATENT_TROPHY: "/images/patent/recognition.png",
PATENT_PREVIEW: "/images/patent/patent-preview.png",
PATENT_THERMAL:"/images/patent/thermal.png",
PATENT_AWARD:"/images/patent/award.png",
PATENT_SUCCESS:"/images/patent/success.png",
  }
};
